### ISSUE TITLE
Python 3 Comptaibility

### ISSUE THREAD

**Issue by anhuong** [wasilak/yamllint-junit#1]
Does this only work with Python 2? I tried to install this with `pip3 install yamllint-junit` and got error
```
Collecting yamllint-junit
  Using cached yamllint-junit-0.5.tar.gz (2.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-install-h7m_i_6j/yamllint-junit/setup.py'"'"'; __file__='"'"'/private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-install-h7m_i_6j/yamllint-junit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-pip-egg-info-of9c2ewk
         cwd: /private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-install-h7m_i_6j/yamllint-junit/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-install-h7m_i_6j/yamllint-junit/setup.py", line 3, in <module>
        from yamllint_junit_bootstrap import bootstrap
      File "/private/var/folders/9b/6n0_krj15rs3z6mcjm417dwr0000gn/T/pip-install-h7m_i_6j/yamllint-junit/yamllint_junit_bootstrap/bootstrap.py", line 85
        print parsed_lines_xml
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(parsed_lines_xml)?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Main error shows `yamllint-junit/yamllint_junit_bootstrap/bootstrap.py", line 85 -- SyntaxError: Missing parentheses in call to 'print'. Did you mean print(parsed_lines_xml)?`

**Comment by cyper85** [comment]
I create a fix and add some tests to your tool.
